### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by maxming2333** [misakuo/weex-language-support#11]
如下错误：

```
Intention Description Dir URL is null: Weex; WeexTagTextCompletion [Plugin: com.taobao.weex.lang]
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Weex; WeexTagTextCompletion [Plugin: com.taobao.weex.lang]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:114)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:151)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.b(IntentionManagerSettings.java:156)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:147)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:78)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.b(IntentionManagerImpl.java:92)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

感觉装了这个插件，其他应用程序会莫名崩溃

**Comment by misakuo** [comment]
有一些描述信息没有打包到插件里，稍后我会release一个新版本来修复该问题

**Comment by misakuo** [comment]
请更新到 [2.0.5](https://plugins.jetbrains.com/plugin/9189-weex-language-support/update/37563)

**Comment by maxming2333** [comment]
重装了插件，还是会报错（2.0.5）

```
Intention Description Dir URL is null: Weex; WeexTagTextCompletion [Plugin: com.taobao.weex.lang]
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Weex; WeexTagTextCompletion [Plugin: com.taobao.weex.lang]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:114)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:151)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.b(IntentionManagerSettings.java:156)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:147)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:78)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.b(IntentionManagerImpl.java:92)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

然后启动后，会导致我的一个阿里内部软件（阿里郎）崩溃，之前的版本也会导致 阿里郎 崩溃

**Comment by maxming2333** [comment]
我的 IDEA 信息

![image](https://user-images.githubusercontent.com/8816730/29052912-822ce488-7c1f-11e7-861a-2c08eae1da01.png)

**Comment by misakuo** [comment]
不好意思，2.0.6版本应该已经修复了该问题，请再更新试一下

**Comment by maxming2333** [comment]
测试通过~
非常感谢
