### ISSUE TITLE
更新了1.1 一直报错。

### ISSUE THREAD

**Issue by cooliean** [misakuo/weex-language-support#4]
下午2:28	NullPointerException: null

下午2:28	NullPointerException: null

下午2:28	NullPointerException: null

下午2:32	NullPointerException: null

下午2:32	NullPointerException: null

下午2:33	NullPointerException: null

**Comment by misakuo** [comment]
贴下详细的错误堆栈

**Comment by cooliean** [comment]
@misakuo 
```java
null
java.lang.NullPointerException
	at com.taobao.weex.annotator.WeexAnnotator.match(WeexAnnotator.java:183)
	at com.taobao.weex.annotator.WeexAnnotator.verifyDataType(WeexAnnotator.java:117)
	at com.taobao.weex.annotator.WeexAnnotator.verifyVarAndFunction(WeexAnnotator.java:169)
	at com.taobao.weex.annotator.WeexAnnotator.checkAttributeValue(WeexAnnotator.java:218)
	at com.taobao.weex.annotator.WeexAnnotator.checkAttributes(WeexAnnotator.java:68)
	at com.taobao.weex.annotator.WeexAnnotator.checkStructure(WeexAnnotator.java:322)
	at com.taobao.weex.annotator.WeexAnnotator.annotate(WeexAnnotator.java:37)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:334)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:293)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:747)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by misakuo** [comment]
@cooliean 出错的地方找到了，但是能不能给一个可以触发错误的we文件？我需要确定一下什么场景下会导致这个问题

**Comment by cooliean** [comment]
@misakuo 
我也不知道那个we可以促发呢。我加了Q群没有反应

**Comment by misakuo** [comment]
@cooliean 335401226 之前写错号码了= =
